In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/customer_churn.csv")

In [4]:
df.head()

,Customer_ID,Age,Tenure_Months,Monthly_Charges,Contract_Type,Support_Calls,Payment_Method,Internet_Service,Churn
0,1,56,35,655,One year,8,Credit Card,Fiber,Yes
1,2,69,51,557,Two year,0,UPI,No Internet,Yes
2,3,46,15,1017,Month-to-month,10,Debit Card,Fiber,No
3,4,32,25,888,Month-to-month,3,Credit Card,No Internet,No
4,5,60,55,823,Month-to-month,0,Credit Card,No Internet,No

In [5]:
df.shape

(1000, 9)

In [6]:
df.dtypes

Customer_ID         int64
Age                 int64
Tenure_Months       int64
Monthly_Charges     int64
Contract_Type         str
Support_Calls       int64
Payment_Method        str
Internet_Service      str
Churn                 str
dtype: object

In [7]:
df.isnull()

,Customer_ID,Age,Tenure_Months,Monthly_Charges,Contract_Type,Support_Calls,Payment_Method,Internet_Service,Churn
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False

In [8]:
df.isnull().sum()

Customer_ID         0
Age                 0
Tenure_Months       0
Monthly_Charges     0
Contract_Type       0
Support_Calls       0
Payment_Method      0
Internet_Service    0
Churn               0
dtype: int64

In [10]:
df.columns.tolist()

['Customer_ID',
 'Age',
 'Tenure_Months',
 'Monthly_Charges',
 'Contract_Type',
 'Support_Calls',
 'Payment_Method',
 'Internet_Service',
 'Churn']

In [11]:
df["Churn"].value_counts()

Churn
No     588
Yes    412
Name: count, dtype: int64

In [12]:
df.describe()

       Customer_ID         Age  Tenure_Months  Monthly_Charges  Support_Calls
count  1000.000000  1000.00000    1000.000000      1000.000000    1000.000000
mean    500.500000    43.81900      31.076000       747.811000       4.954000
std     288.819436    14.99103      17.207391       256.557024       3.197203
min       1.000000    18.00000       1.000000       300.000000       0.000000
25%     250.750000    31.00000      17.000000       535.750000       2.000000
50%     500.500000    44.00000      32.000000       751.500000       5.000000
75%     750.250000    56.00000      46.000000       965.250000       8.000000
max    1000.000000    69.00000      60.000000      1199.000000      10.000000

In [13]:
df["Contract_Type"].value_counts()

Contract_Type
Month-to-month    351
One year          326
Two year          323
Name: count, dtype: int64

In [14]:
df["Payment_Method"].value_counts()

Payment_Method
Debit Card       255
UPI              254
Credit Card      246
Bank Transfer    245
Name: count, dtype: int64

In [15]:
df["Internet_Service"].value_counts()

Internet_Service
No Internet    346
Fiber          338
DSL            316
Name: count, dtype: int64